language: python
python:
- 3.8
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run pytest --cov=player_on_court
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
- poetry build -f sdist
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
after_success:
  poetry run coveralls